server:
  port: 8080
  host: 0.0.0.0

app:
    name: "Fili Online Store"

db:
  source: jdbc
  connection:
    url: jdbc:mysql://mysql8:3306/catalogdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    poolName: hikariPool
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: "SELECT 0"
    insert-product-category: "INSERT INTO product_categories(name) VALUES(?)"
    insert-product: "INSERT INTO products(name, category_id) VALUES(?, ?)"
    select-all-product-categories: "SELECT * FROM product_categories"
    select-all-products: "SELECT * FROM products"
