version: '3.1'

services:
  mysql8:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - fili-net
    volumes:
      - fili-db:/var/lib/mysql-catalog-service
      - ./catalog-service/db-scripts/01_create_schema.sql:/docker-entrypoint-initdb.d/01_create_schema.sql
      - ./catalog-service/db-scripts/02_init_data.sql:/docker-entrypoint-initdb.d/02_init_data.sql

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    image: catalog-service-filimp:1.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fili-net
    external_links:
        - mysql8:mysql8
    depends_on:
      - mysql8

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  fili-db:
    driver: local

networks:
  fili-net:
    driver: bridge