apiVersion: skaffold/v4beta8

kind: Config

metadata:
  name: filimp
build:
  tagPolicy:
    envTemplate:
      template: "{{.FILIMP_VERSION}}"
  artifacts:
    - image: catalog-service-filimp
      context: catalog-service
      docker:
        dockerfile: Dockerfile
        noCache: true
manifests:
  rawYaml:
    - catalog-service/app.yaml
