kind: Service
apiVersion: v1
metadata:
  name: catalog-service-filimp
  labels:
    app: catalog-service-filimp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: catalog-service-filimp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog-service-filimp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-filimp
  template:
    metadata:
      labels:
        app: catalog-service-filimp
        version: v1
    spec:
      containers:
      - name: catalog-service-filimp
        image: catalog-service-filimp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
