kind: Service
apiVersion: v1
metadata:
  name: xxx-service-filimp
  labels:
    app: xxx-service-filimp
spec:
  type: NodePort
  selector:
    app: xxx-service-filimp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: xxx-service-filimp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-service-filimp
  template:
    metadata:
      labels:
        app: xxx-service-filimp
        version: v1
    spec:
      containers:
      - name: xxx-service-filimp
        image: xxx-service-filimp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
